### ISSUE TITLE
UnhandledPromiseRejectionWarning in contract subscriber

### ISSUE THREAD

**Issue by c-o-l-o-r** [c-o-l-o-r/DelphiAPI#23]
```
(node:1707) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sendToQueue' of null
  at Promise (/usr/src/app/node_modules/wrappitmq/lib/WorkQueue.js:56:20)
  at new Promise (<anonymous>)
  at WorkQueue.enqueue (/usr/src/app/node_modules/wrappitmq/lib/WorkQueue.js:51:12)
  at contract_queue.consume (/usr/src/app/contract_subscriber.js:36:26)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:160:7)
(node:1707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
```

**Comment by lightclient** [comment]
still not 100% of the issue, but it seems to be resolved by closing the queue connection after the subscriber delay

**Comment by BKDaugherty** [comment]
You the goat @c-o-l-o-r

**Comment by lightclient** [comment]
@BKDaugherty nice to see you in these parts!
